-- Drop tables
-- DROP TABLE publication_authors;
-- DROP TABLE authors;
-- DROP TABLE ee;
-- DROP TABLE publications;

-- Create tables
CREATE TABLE PUBLICATIONS (
  ID INT PRIMARY KEY,
  TYPE VARCHAR(255),
  TITLE VARCHAR(255),
  PAGES VARCHAR(30),
  YEAR INT,
  BOOKTITLE VARCHAR(255),
  CROSSREF VARCHAR(255),
  SCHOOL VARCHAR(255),
  VOLUME INT,
  JOURNAL VARCHAR(255),
  NUM INT,
  URL VARCHAR(255)
);

CREATE TABLE EE (
  ID INT PRIMARY KEY,
  URL VARCHAR(255),
  PUBLICATION_ID INT,
  FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATIONS(ID)
);

CREATE TABLE AUTHORS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE PUBLICATION_AUTHORS (
  ID INT PRIMARY KEY,
  PUBLICATION_ID INT,
  AUTHOR_ID INT,
  FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATIONS(ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

-- Insert data

--