-- Liste de tous les livres (type "Book") :

CREATE OR REPLACE FUNCTION GET_BOOKS RETURN NESTED_TABLE_TYPE_BOOKS IS
    BOOK_LIST NESTED_TABLE_TYPE_BOOKS;
BEGIN
    FOR I IN (
        SELECT
            *
        FROM
            PUBLICATIONS
    ) LOOP
        IF I.TYPE = 'Book' THEN
            BOOK_LIST.EXTEND;
            BOOK_LIST(BOOK_LIST.COUNT) := I;
        END IF;
    END LOOP;
    RETURN BOOK_LIST;
END GET_BOOKS;
DECLARE
    BOOK_LIST PUBLICATIONS_NT;
BEGIN
    BOOKS_LIST := GET_BOOKS();
    FOR I IN 1..BOOK_LIST.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(BOOK_LIST(I).TITLE);
    END LOOP;
END;