DECLARE
    CURSOR BOOKS_CUR IS
        SELECT
            TITLE
        FROM
            PUBLICATIONS
        WHERE
            TYPE = 'Book';
BEGIN
    FOR BOOK IN BOOKS_CUR LOOP
        DBMS_OUTPUT.PUT_LINE(BOOK.TITLE);
    END LOOP;
END;