INSERT INTO publications (id,type,title,pages,year,volume,journal,url) VALUES ("20","Journal","PROADAPT: Proactive framework for adaptive partitioning for big data warehouses.",102102,2022,142,"Data Knowl. Eng.","db/journals/dke/dke142.html#BenkridBMO22");
INSERT INTO publications (id,type,title,year,volume,journal,number,url) VALUES ("19","Preface","Towards understanding and harnessing the potential of Africa in digitalization.",2021,33,"Concurr. Comput. Pract. Exp.",1,"db/journals/concurrency/concurrency33.html#BenkridMBLB21");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("1","Article","Towards an Adaptive Multidimensional Partitioning for Accelerating Spark SQL.","27-38",2021,"DaWaK","conf/dawak/2021","db/conf/dawak/dawak2021.html#BenkridBM021");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("18","Article","A Genetic Optimization Physical Planner for Big Data Warehouses.","406-412",2020,"IEEE BigData","conf/bigdataconf/2020","db/conf/bigdataconf/bigdataconf2020.html#BenkridMB020");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("17","Article","Vers une Conception des Entrep&#244;ts de Donn&#233;es Parall&#232;les Autonomes.","109-124",2019,"EDA","conf/eda/2019","db/conf/eda/eda2019.html#BenkridB19");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("16","Article","A Framework for Designing Autonomous Parallel Data Warehouses.","97-104",2019,"ICA3PP (2)","conf/ica3pp/2019-2","db/conf/ica3pp/ica3pp2019-2.html#BenkridB19");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("15","Article","Vers l'am&#233;lioration du processus d&#233;cisionnel par l'int&#233;gration des donn&#233;es sociales.","123-138",2017,"EDA","conf/eda/2017","db/conf/eda/eda2017.html#BenkridBBSZL17");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("14","Article","HYPAD: Hyper-Graph-Driven Approach for Parallel Data Warehouse Design.","770-783",2015,"ICA3PP (4)","conf/ica3pp/2015-4","db/conf/ica3pp/ica3pp2015-4.html#BoukorcaBB15");
INSERT INTO publications (id,type,title,year,school) VALUES ("13","Book","Le d&#233;ploiement, une phase &#224; part enti&#232;re dans le cycle de vie des entrep&#244;ts de donn&#233;es : application aux plateformes parall&#232;les. (Deployment, full phase in the data warehouse life cycle : application to parallel platforms).",2014,"&#201;cole nationale sup&#233;rieure de m&#233;canique et d'a&#233;rotechnique, Chasseneuil-du-Poitou, Poitiers, France");
INSERT INTO publications (id,type,title,pages,year,volume,journal,crossref,url) VALUES ("12","Journal","A Global Paradigm for Designing Parallel Relational Data Warehouses in Distributed Environments.","64-101",2014,15,"Trans. Large Scale Data Knowl. Centered Syst.","journals/tlsdkcs/2014-15","db/journals/tlsdkcs/tlsdkcs15.html#BenkridBC14");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("11","Article","Designing Parallel Relational Data Warehouses: A Global, Comprehensive Approach.","141-150",2013,"ADBIS (2)","conf/adbis/2013-2","db/conf/adbis/adbis2013-2.html#BenkridBC13");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("10","Article","Omniscience dans la Conception des Entrep&#244;ts de Donn&#233;es Parall&#232;les sur un Cluster.","43-52",2013,"EDA","conf/eda/2013","db/conf/eda/eda2013.html#BenkridBC13");
INSERT INTO publications (id,type,title,pages,year,volume,journal,number,url) VALUES ("09","Journal","Effectively and Efficiently Designing and Querying Parallel Relational Data Warehouses on Heterogeneous Database Clusters: The F&#38;A Approach.","17-51",2012,23,"J. Database Manag.",4,"db/journals/jdm/jdm23.html#BellatrecheCB12");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("08","Article","The F&#38;A Methodology and Its Experimental Validation on a Real-Life Parallel Processing Database System.","114-121",2012,"CISIS","conf/cisis/2012","db/conf/cisis/cisis2012.html#BellatrecheBCCG12");
INSERT INTO publications (id,type,title,pages,year,volume,journal,number,url) VALUES ("07","Journal","Une d&#233;marche conjointe de fragmentation et de placement dans le cadre des entrep&#244;ts de donn&#233;es parall&#232;les.","953-973",2011,30,"Tech. Sci. Informatiques",8,"db/journals/tsi/tsi30.html#BenkridB11");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("06","Article","Verification of Partitioning and Allocation Techniques on Teradata DBMS.","158-169",2011,"ICA3PP (1)","conf/ica3pp/2011-1","db/conf/ica3pp/ica3pp2011-1.html#BellatrecheBGCC11");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("05","Article","&#38;: A Methodology for Effectively and Efficiently Designing Parallel Relational Data Warehouses on Heterogenous Database Clusters.","89-104",2010,"DaWaK","conf/dawak/2010","db/conf/dawak/dawak2010.html#BellatrecheCB10");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("04","Article","Query Optimization over Parallel Relational Data Warehouses in Distributed Environments by Simultaneous Fragmentation and Allocation.","124-135",2010,"ICA3PP (1)","conf/ica3pp/2010-1","db/conf/ica3pp/ica3pp2010-1.html#BellatrecheCB10");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("03","Article","A Joint Design Approach of Partitioning and Allocation in Parallel Data Warehouses.","99-110",2009,"DaWaK","conf/dawak/2009","db/conf/dawak/dawak2009.html#BellatrecheB09");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("02","Article","Une d&#233;marche conjointe de fragmentation et de placement dans le cadre des entrep&#244;ts de donn&#233;es parall&#232;les.","91-106",2009,"EDA","conf/eda/2009","db/conf/eda/eda2009.html#BenkridB09");
INSERT INTO publications (id,type,title,pages,year,booktitle,crossref,url) VALUES ("01","Article","A Combined Selection of Fragmentation and Allocation Schemes in Parallel Data Warehouses.","370-374",2008,"DEXA Workshops","conf/dexaw/2008","db/conf/dexaw/dexaw2008.html#BenkridBD08");
INSERT INTO authors (id,name) VALUES (1,"Soumia Benkrid");
INSERT INTO authors (id,name) VALUES (2,"Ladjel Bellatreche");
INSERT INTO authors (id,name) VALUES (3,"Yacine Mestoui");
INSERT INTO authors (id,name) VALUES (4,"Carlos Ordonez 0001");
INSERT INTO authors (id,name) VALUES (5,"Rim Moussa");
INSERT INTO authors (id,name) VALUES (6,"Hassan Badir");
INSERT INTO authors (id,name) VALUES (7,"Moussa Lo");
INSERT INTO authors (id,name) VALUES (8,"Redouane Boucenna");
INSERT INTO authors (id,name) VALUES (9,"Dihia Boulegane");
INSERT INTO authors (id,name) VALUES (10,"Younes Sennadj");
INSERT INTO authors (id,name) VALUES (11,"Chahnez Zakaria");
INSERT INTO authors (id,name) VALUES (12,"Lynda Said L'Hadj");
INSERT INTO authors (id,name) VALUES (13,"Ahc&#232;ne Boukorca");
INSERT INTO authors (id,name) VALUES (14,"Alfredo Cuzzocrea");
INSERT INTO authors (id,name) VALUES (15,"Alain Crolotte");
INSERT INTO authors (id,name) VALUES (16,"Ahmad Ghazal");
INSERT INTO authors (id,name) VALUES (17,"Habiba Drias");
INSERT INTO ee (publication_id, url) VALUES (20,'https://doi.org/10.1016/j.datak.2022.102102');
INSERT INTO ee (publication_id, url) VALUES (19,'https://doi.org/10.1002/cpe.6127');
INSERT INTO ee (publication_id, url) VALUES (1,'https://doi.org/10.1007/978-3-030-86534-4_3');
INSERT INTO ee (publication_id, url) VALUES (18,'https://doi.org/10.1109/BigData50022.2020.9378196');
INSERT INTO ee (publication_id, url) VALUES (17,'http://editions-rnti.fr/?inprocid=1002548');
INSERT INTO ee (publication_id, url) VALUES (16,'https://doi.org/10.1007/978-3-030-38961-1_9');
INSERT INTO ee (publication_id, url) VALUES (15,'http://editions-rnti.fr/?inprocid=1002344');
INSERT INTO ee (publication_id, url) VALUES (14,'https://doi.org/10.1007/978-3-319-27140-8_53');
INSERT INTO ee (publication_id, url) VALUES (13,'https://tel.archives-ouvertes.fr/tel-01127551');
INSERT INTO ee (publication_id, url) VALUES (12,'https://doi.org/10.1007/978-3-662-45761-0_3');
INSERT INTO ee (publication_id, url) VALUES (11,'https://doi.org/10.1007/978-3-319-01863-8_16');
INSERT INTO ee (publication_id, url) VALUES (10,'http://editions-rnti.fr/?inprocid=1001894');
INSERT INTO ee (publication_id, url) VALUES (09,'https://doi.org/10.4018/jdm.2012100102');
INSERT INTO ee (publication_id, url) VALUES (08,'https://doi.org/10.1109/CISIS.2012.95');
INSERT INTO ee (publication_id, url) VALUES (08,'http://doi.ieeecomputersociety.org/10.1109/CISIS.2012.95');
INSERT INTO ee (publication_id, url) VALUES (07,'https://doi.org/10.3166/tsi.30.953-973');
INSERT INTO ee (publication_id, url) VALUES (06,'https://doi.org/10.1007/978-3-642-24650-0_14');
INSERT INTO ee (publication_id, url) VALUES (05,'https://doi.org/10.1007/978-3-642-15105-7_8');
INSERT INTO ee (publication_id, url) VALUES (04,'https://doi.org/10.1007/978-3-642-13119-6_11');
INSERT INTO ee (publication_id, url) VALUES (03,'https://doi.org/10.1007/978-3-642-03730-6_9');
INSERT INTO ee (publication_id, url) VALUES (02,'http://editions-rnti.fr/?inprocid=1000864');
INSERT INTO ee (publication_id, url) VALUES (01,'https://doi.org/10.1109/DEXA.2008.63');
INSERT INTO ee (publication_id, url) VALUES (01,'http://doi.ieeecomputersociety.org/10.1109/DEXA.2008.63');
INSERT INTO publication_authors (publication_id, author_id) VALUES (20, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (20, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (20, (SELECT id FROM authors WHERE name = "Yacine Mestoui"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (20, (SELECT id FROM authors WHERE name = "Carlos Ordonez 0001"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (19, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (19, (SELECT id FROM authors WHERE name = "Rim Moussa"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (19, (SELECT id FROM authors WHERE name = "Hassan Badir"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (19, (SELECT id FROM authors WHERE name = "Moussa Lo"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (19, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (1, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (1, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (1, (SELECT id FROM authors WHERE name = "Yacine Mestoui"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (1, (SELECT id FROM authors WHERE name = "Carlos Ordonez 0001"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (18, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (18, (SELECT id FROM authors WHERE name = "Yacine Mestoui"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (18, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (18, (SELECT id FROM authors WHERE name = "Carlos Ordonez 0001"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (17, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (17, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (16, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (16, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Redouane Boucenna"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Dihia Boulegane"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Younes Sennadj"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Chahnez Zakaria"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (15, (SELECT id FROM authors WHERE name = "Lynda Said L'Hadj"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (14, (SELECT id FROM authors WHERE name = "Ahc&#232;ne Boukorca"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (14, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (14, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (13, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (12, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (12, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (12, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (11, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (11, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (11, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (10, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (10, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (10, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (09, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (09, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (09, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (08, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (08, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (08, (SELECT id FROM authors WHERE name = "Alain Crolotte"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (08, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (08, (SELECT id FROM authors WHERE name = "Ahmad Ghazal"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (07, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (07, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (06, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (06, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (06, (SELECT id FROM authors WHERE name = "Ahmad Ghazal"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (06, (SELECT id FROM authors WHERE name = "Alain Crolotte"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (06, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (05, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (05, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (05, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (04, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (04, (SELECT id FROM authors WHERE name = "Alfredo Cuzzocrea"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (04, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (03, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (03, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (02, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (02, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (01, (SELECT id FROM authors WHERE name = "Soumia Benkrid"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (01, (SELECT id FROM authors WHERE name = "Ladjel Bellatreche"));
INSERT INTO publication_authors (publication_id, author_id) VALUES (01, (SELECT id FROM authors WHERE name = "Habiba Drias"));
